# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentconf" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "d3ad362b7820e898383e2a4a89fd0299b394a58523f9fbb90f6ee0a7a14369ef"
      url "https://github.com/AviroopPaul/agentconf/releases/download/v#{version}/agentconf_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ce0b5c6edd584de1cccc17523e67444797ab747da705c95cd6cf1bb17e4142af"
      url "https://github.com/AviroopPaul/agentconf/releases/download/v#{version}/agentconf_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "42b61556b37ca82273ceffcc185cef74961218a84becd5ceb09c13524dcc3208"
      url "https://github.com/AviroopPaul/agentconf/releases/download/v#{version}/agentconf_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "65c6addba5ecbf066d3e29b20702438e37abc8c04e50030f2106e647a7ded4a2"
      url "https://github.com/AviroopPaul/agentconf/releases/download/v#{version}/agentconf_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentconf"
  desc "Read-only UI over your coding agents' config directories"
  homepage "https://github.com/AviroopPaul/agentconf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentconf"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentconf"]
    end
  end

  # No zap stanza required
end
