# Generated by scripts/release.sh in the (private) Reader source repo. Do not edit by hand.
# A cask (not a formula) so installs need no Command Line Tools and nothing is built.
# Token is "reader-app" because homebrew/cask already has "reader" (Readwise Reader).
cask "reader-app" do
  version "1.0.2"

  on_arm do
    sha256 "82baac937678a280c0913989690340297fd8eb3480eb1ce880a825907048cb23"
    url "https://github.com/AviroopPaul/homebrew-tap/releases/download/reader-v#{version}/reader_#{version}_darwin_arm64.tar.gz"
  end
  on_intel do
    sha256 "ebab9069757408dcc067530097068b16cc4eb17697368586b4bd8011c62c18ab"
    url "https://github.com/AviroopPaul/homebrew-tap/releases/download/reader-v#{version}/reader_#{version}_darwin_amd64.tar.gz"
  end

  name "Reader"
  desc "Fast, private, local EPUB & PDF reader with highlights, notes and bookmarks"
  homepage "https://avirooppaul.github.io/homebrew-tap/reader/"

  livecheck do
    skip "Released with scripts/release.sh"
  end

  depends_on macos: ">= :ventura"
  depends_on formula: "mkcert"
  depends_on formula: "nginx"
  depends_on formula: "tmux"

  binary "reader_#{version}/bin/reader"
  binary "reader_#{version}/bin/readerctl"

  postflight do
    # unsigned CLI binaries: drop the download quarantine so Gatekeeper lets them run
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
  end

  caveats <<~EOS
    Finish setting up Reader (nginx site, trusted local HTTPS certificate,
    start now and at every login):

      readerctl setup

    Then open https://reader.localhost. Your library lives in ~/Reader.
    macOS asks for your password once to trust the local certificate.
    More: readerctl help. Remove: readerctl uninstall && brew uninstall --cask reader-app
  EOS

  zap trash: "~/.config/reader"
end
