# Generated by scripts/release.sh in the (private) Reader source repo. Do not edit by hand.
class Reader < Formula
  desc "Fast, private, local EPUB & PDF reader with highlights, notes and bookmarks"
  homepage "https://avirooppaul.github.io/homebrew-tap/reader/"
  version "1.0.1"

  on_arm do
    url "https://github.com/AviroopPaul/homebrew-tap/releases/download/reader-v1.0.1/reader_1.0.1_darwin_arm64.tar.gz"
    sha256 "53f6ca26fa8ea6e5476fe3516b04a4e52ebbc97cbb703cc525a43e155b8c2d03"
  end
  on_intel do
    url "https://github.com/AviroopPaul/homebrew-tap/releases/download/reader-v1.0.1/reader_1.0.1_darwin_amd64.tar.gz"
    sha256 "a419a0657ca8a65106b845d20921ea20e7bafec911bb133a3c22f0027dd3ae52"
  end

  depends_on :macos
  depends_on "mkcert"
  depends_on "nginx"
  depends_on "tmux"

  def install
    bin.install "bin/reader", "bin/readerctl"
    pkgshare.install Dir["share/reader/*"]
    doc.install "README.md", "THIRD_PARTY_NOTICES.md"
  end

  def caveats
    <<~EOS
      Finish setting up Reader (nginx site, trusted local HTTPS certificate,
      start now and at every login):

        readerctl setup

      Then open https://reader.localhost — your library lives in ~/Reader.
      macOS will ask for your password once to trust the local certificate.
      More: readerctl help  ·  Remove: readerctl uninstall && brew uninstall reader
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/reader version")
    assert_path_exists pkgshare/"deploy/nginx-reader.conf"
    assert_match "readerctl", shell_output("#{bin}/readerctl help")
  end
end
